'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace LayoutControl_Ex.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As LayoutControl_Ex.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New LayoutControl_Ex.Properties.Settings())), LayoutControl_Ex.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return LayoutControl_Ex.Properties.Settings.defaultInstance
            End Get
        End Property
    End Class
End Namespace
